Fix v2 error in examples/calculator.py (#22)
As-is this example errors with:

Error: type mismatch - expected an instance of f64, found an instance of i64.
44 |     calculator.display /= num

The docs are updated to use `//=` instead, and with that change it compiles correctly